import 'package:flutter/material.dart';

import '../models/admin_resource.dart';

const organizationLookup = AdminLookup(
  endpoint: '/api/admin/organizations',
  labelKeys: ['display_name', 'legal_name', 'organization_type'],
);

const userLookup = AdminLookup(
  endpoint: '/api/admin/users',
  labelKeys: ['email', 'full_name', 'role_code'],
  limit: 1000,
  showIdInDropdown: false,
);

const organizationContactLookup = AdminLookup(
  endpoint: '/api/admin/organization-contacts',
  labelKeys: ['full_name', 'email', 'contact_type'],
  limit: 2000,
  showIdInDropdown: false,
);

const referenceDomainLookup = AdminLookup(
  endpoint: '/api/admin/reference-domains',
  labelKeys: ['code', 'name'],
);

const productFamilyLookup = AdminLookup(
  endpoint: '/api/admin/product-families',
  labelKeys: ['code', 'name'],
);

const catalogItemLookup = AdminLookup(
  endpoint: '/api/admin/catalog-items',
  labelKeys: ['base_code', 'name'],
  limit: 2000,
);

const catalogItemNameLookup = AdminLookup(
  endpoint: '/api/admin/catalog-items',
  // Several catalog items legitimately share the same human name.
  // Keep UUID hidden, but include the business code so lookup dropdowns are not ambiguous.
  labelKeys: ['base_code', 'name'],
  limit: 2000,
  showIdInDropdown: false,
);

const catalogVariantLookup = AdminLookup(
  endpoint: '/api/admin/catalog-variants',
  labelKeys: ['variant_sku', 'system_name', 'color_name', 'length_mm', 'article_no'],
  limit: 3000,
  showIdInDropdown: false,
);

const priceListLookup = AdminLookup(
  endpoint: '/api/admin/price-lists',
  labelKeys: ['code', 'name', 'scope_code', 'currency'],
  limit: 1000,
  showIdInDropdown: false,
);

const salesPriceListLookup = AdminLookup(
  endpoint: '/api/admin/sales-price-lists',
  labelKeys: ['code', 'name', 'scope_code', 'currency'],
  limit: 1000,
  showIdInDropdown: false,
);

const configuratorTemplateLookup = AdminLookup(
  endpoint: '/api/admin/configurator-templates',
  labelKeys: ['code', 'name', 'version', 'status_code'],
  limit: 1000,
  showIdInDropdown: false,
);

const roofModelLookup = AdminLookup(
  endpoint: '/api/admin/roof-models',
  labelKeys: ['code', 'name'],
  limit: 1000,
  showIdInDropdown: false,
);

const materialPriceDimensionLookup = AdminLookup(
  endpoint: '/api/admin/material-price-dimensions',
  labelKeys: ['code', 'name', 'unit_code'],
  limit: 1000,
  showIdInDropdown: false,
);


// BEGIN quote admin block: admin-registry-quote-lookups-v2
const quoteLookup = AdminLookup(
  endpoint: '/api/admin/quotes',
  labelKeys: ['quote_no', 'status_code', 'created_at'],
  limit: 1000,
  showIdInDropdown: false,
);

const quoteStatusOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'draft', label: 'Draft'),
  AdminSelectOption(value: 'approved', label: 'Approved'),
  AdminSelectOption(value: 'sent', label: 'Sent'),
  AdminSelectOption(value: 'accepted', label: 'Accepted'),
  AdminSelectOption(value: 'rejected', label: 'Rejected'),
  AdminSelectOption(value: 'cancelled', label: 'Cancelled'),
];

const quoteOrderTypeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'offer', label: 'Offer'),
  AdminSelectOption(value: 'order', label: 'Order'),
];

// END quote admin block: admin-registry-quote-lookups-v2
const activeFilterOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'true', label: 'Yes'),
  AdminSelectOption(value: 'false', label: 'No'),
];

const globalRoleOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'sysadmin', label: 'Sysadmin'),
  AdminSelectOption(value: 'admin', label: 'Admin'),
  AdminSelectOption(value: 'manager', label: 'Manager'),
  AdminSelectOption(value: 'viewer', label: 'Viewer'),
];

const organizationRoleOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'sysadmin', label: 'Sysadmin (VD only)'),
  AdminSelectOption(value: 'admin', label: 'Admin'),
  AdminSelectOption(value: 'manager', label: 'Manager'),
  AdminSelectOption(value: 'sales', label: 'Sales'),
  AdminSelectOption(value: 'partner', label: 'Partner'),
  AdminSelectOption(value: 'viewer', label: 'Viewer'),
];

const contactTypeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'general', label: 'General'),
  AdminSelectOption(value: 'owner', label: 'Owner'),
  AdminSelectOption(value: 'sales', label: 'Sales'),
  AdminSelectOption(value: 'office', label: 'Office'),
  AdminSelectOption(value: 'configurator', label: 'Configurator'),
  AdminSelectOption(value: 'billing', label: 'Billing'),
  AdminSelectOption(value: 'delivery', label: 'Delivery'),
  AdminSelectOption(value: 'service', label: 'Service'),
  AdminSelectOption(value: 'other', label: 'Other'),
];

const organizationTypeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'internal', label: 'Internal'),
  AdminSelectOption(value: 'dealer', label: 'Dealer'),
  AdminSelectOption(value: 'b2b_customer', label: 'B2B customer'),
  AdminSelectOption(value: 'end_customer', label: 'End customer'),
  AdminSelectOption(value: 'supplier', label: 'Supplier'),
  AdminSelectOption(value: 'brand', label: 'Brand'),
  AdminSelectOption(value: 'other', label: 'Other'),
];

const catalogItemTypeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'profile', label: 'Profile'),
  AdminSelectOption(value: 'glass', label: 'Glass'),
  AdminSelectOption(value: 'polycarbonate', label: 'Polycarbonate'),
  AdminSelectOption(value: 'accessory', label: 'Accessory'),
  AdminSelectOption(value: 'service', label: 'Service'),
  AdminSelectOption(value: 'set', label: 'Set'),
  AdminSelectOption(value: 'awning', label: 'Awning'),
  AdminSelectOption(value: 'coating', label: 'Coating'),
  AdminSelectOption(value: 'other', label: 'Other'),
];

const mediaKindOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'image', label: 'Image'),
  AdminSelectOption(value: 'pdf', label: 'PDF'),
  AdminSelectOption(value: 'drawing', label: 'Drawing'),
  AdminSelectOption(value: 'datasheet', label: 'Datasheet'),
  AdminSelectOption(value: 'barcode', label: 'Barcode'),
  AdminSelectOption(value: 'other', label: 'Other'),
];

const unitOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'piece', label: 'Piece'),
  AdminSelectOption(value: 'meter', label: 'Meter'),
  AdminSelectOption(value: 'sqm', label: 'Square meter'),
  AdminSelectOption(value: 'kg', label: 'Kilogram'),
  AdminSelectOption(value: 'hour', label: 'Hour'),
  AdminSelectOption(value: 'month', label: 'Month'),
];

const statusOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'draft', label: 'Draft'),
  AdminSelectOption(value: 'published', label: 'Published'),
  AdminSelectOption(value: 'archived', label: 'Archived'),
];

const scopeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'customer', label: 'Customer'),
  AdminSelectOption(value: 'b2b', label: 'B2B'),
  AdminSelectOption(value: 'internal', label: 'Internal'),
  AdminSelectOption(value: 'supplier', label: 'Supplier'),
  AdminSelectOption(value: 'other', label: 'Other'),
];

const systemOptionPriceListPurposeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'calculator_options', label: 'Calculator options'),
];

const systemSettingCodeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'head_organization', label: 'Head organization'),
];

const priceListScopeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'sales', label: 'Sales'),
  AdminSelectOption(value: 'retail_sales', label: 'Retail sales'),
  AdminSelectOption(value: 'dealer_sales', label: 'Dealer sales'),
  AdminSelectOption(value: 'discounted_sales', label: 'Discounted sales'),
  AdminSelectOption(value: 'internal_margin', label: 'Internal margin'),
  AdminSelectOption(value: 'installation_cost', label: 'Installation cost'),
  AdminSelectOption(value: 'purchase', label: 'Purchase'),
  AdminSelectOption(value: 'customer', label: 'Customer'),
  AdminSelectOption(value: 'b2b', label: 'B2B'),
  AdminSelectOption(value: 'internal', label: 'Internal'),
  AdminSelectOption(value: 'supplier', label: 'Supplier'),
  AdminSelectOption(value: 'other', label: 'Other'),
];

const templateTypeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'pdf', label: 'PDF'),
  AdminSelectOption(value: 'html', label: 'HTML'),
  AdminSelectOption(value: 'spreadsheet', label: 'Spreadsheet'),
  AdminSelectOption(value: 'docx', label: 'DOCX'),
  AdminSelectOption(value: 'other', label: 'Other'),
];

const moduleTypeOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'form_section', label: 'Form section'),
  AdminSelectOption(value: 'range_editor', label: 'Range editor'),
  AdminSelectOption(value: 'matrix', label: 'Matrix'),
  AdminSelectOption(value: 'output_block', label: 'Output block'),
  AdminSelectOption(value: 'document_data', label: 'Document data'),
  AdminSelectOption(value: 'other', label: 'Other'),
];

const parserKindOptions = <AdminSelectOption>[
  AdminSelectOption(value: 'roof_matrix', label: 'Roof matrix'),
  AdminSelectOption(value: 'height_width_grid', label: 'Height × width grid'),
  AdminSelectOption(value: 'width_bucket_depth_grid', label: 'Width bucket × depth grid'),
  AdminSelectOption(value: 'fly_matrix', label: 'Fly matrix'),
  AdminSelectOption(value: 'simple_depth_width_grid', label: 'Simple depth × width grid'),
  AdminSelectOption(value: 'unknown', label: 'Unknown'),
];

const dashboardResource = AdminResourceDefinition(
  key: 'dashboard',
  title: 'Dashboard',
  endpoint: '/dashboard',
  icon: Icons.space_dashboard_rounded,
  supportsCreate: false,
  supportsEdit: false,
  columns: [],
  formFields: [],
  description: 'Обзор доменных модулей configurator и быстрые переходы в справочники.',
);

const calculatorWorkspaceResource = AdminResourceDefinition(
      key: 'calculator_workspace',
      title: 'Calculator Workspace',
      endpoint: '/api/internal/calculator',
      icon: Icons.calculate_outlined,
      supportsCreate: false,
      supportsEdit: false,
      supportsDelete: false,
      columns: [],
      formFields: [],
      description: 'Внутренний пошаговый конфигуратор и workspace для отладки расчетов.',
    );

const adminNavGroups = <AdminNavGroup>[


  AdminNavGroup(
    key: 'system_settings',
    title: 'System Settings',
    icon: Icons.admin_panel_settings_outlined,
    resources: [
      AdminResourceDefinition(
        key: 'system_settings',
        title: 'System Settings',
        endpoint: '/api/admin/system-settings',
        icon: Icons.settings_applications_outlined,
        requiresSysadmin: true,
        supportsDelete: false,
        columns: [
          AdminColumn(key: 'setting_code', label: 'Setting', isPrimary: true, flex: 2),
          AdminColumn(key: 'organization_id', label: 'Organization', flex: 2, lookup: organizationLookup),
          AdminColumn(key: 'notes', label: 'Notes', flex: 3),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'setting_code', label: 'Setting', options: systemSettingCodeOptions),
          AdminResourceFilter(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(
            key: 'setting_code',
            label: 'Setting',
            options: systemSettingCodeOptions,
            helperText: 'For the main organization use head_organization.',
          ),
          AdminField(
            key: 'organization_id',
            label: 'Head organization',
            lookup: organizationLookup,
            helperText: 'Main internal organization used instead of the previously hard-coded VD.',
          ),
          AdminField(key: 'value_json', label: 'Value JSON', type: AdminFieldType.json),
          AdminField(key: 'notes', label: 'Notes', type: AdminFieldType.longText),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        description: 'Системные параметры платформы. Сейчас используется для выбора головной организации.',
      ),
      AdminResourceDefinition(
        key: 'system_option_price_lists',
        title: 'Option Price Lists',
        endpoint: '/api/admin/system-option-price-lists',
        icon: Icons.playlist_add_check_outlined,
        requiresSysadmin: true,
        columns: [
          AdminColumn(key: 'purpose_code', label: 'Purpose', isPrimary: true, flex: 2),
          AdminColumn(key: 'price_list_id', label: 'Sales price list', flex: 3, lookup: salesPriceListLookup),
          AdminColumn(key: 'sort_order', label: 'Sort'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'purpose_code', label: 'Purpose', options: systemOptionPriceListPurposeOptions),
          AdminResourceFilter(key: 'price_list_id', label: 'Sales price list', lookup: salesPriceListLookup),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(
            key: 'purpose_code',
            label: 'Purpose',
            options: systemOptionPriceListPurposeOptions,
            helperText: 'calculator_options = price lists used for pricing calculator Options.',
          ),
          AdminField(
            key: 'price_list_id',
            label: 'Sales price list',
            lookup: salesPriceListLookup,
            helperText: 'Only active price lists with scope_code = sales are shown here.',
          ),
          AdminField(key: 'sort_order', label: 'Sort order', type: AdminFieldType.number),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show price list',
            targetResourceKey: 'price_lists',
            filterKey: 'id',
            sourceValueKey: 'price_list_id',
            selectTargetRow: true,
            icon: Icons.request_quote_outlined,
          ),
        ],
        description: 'Прайслисты scope_code=sales, из которых калькулятор берет цены для выбранных Options.',
      ),
    ],
  ),

  AdminNavGroup(
      key: 'calculator',
      title: 'Calculator',
      icon: Icons.calculate_outlined,
      resources: [calculatorWorkspaceResource],
      ),


// BEGIN quote admin block: admin-registry-quote-nav-v2

  AdminNavGroup(
    key: 'quotes',
    title: 'Quotes',
    icon: Icons.request_quote_outlined,
    resources: [
      AdminResourceDefinition(
        key: 'quotes',
        title: 'Quotes',
        endpoint: '/api/admin/quotes',
        icon: Icons.request_quote_outlined,
        supportsCreate: false,
        supportsEdit: false,
        supportsDelete: false,
        columns: [
          AdminColumn(key: 'quote_no', label: 'Quote no', isPrimary: true, flex: 2),
          AdminColumn(key: 'status_code', label: 'Status'),
          AdminColumn(key: 'order_type_code', label: 'Type'),
          AdminColumn(key: 'buyer_organization_id', label: 'Buyer', flex: 2, lookup: organizationLookup),
          AdminColumn(key: 'configurator_template_id', label: 'Template', flex: 2, lookup: configuratorTemplateLookup),
          AdminColumn(key: 'currency', label: 'Currency'),
          AdminColumn(key: 'quote_date', label: 'Date'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'seller_organization_id', label: 'Seller', lookup: organizationLookup),
          AdminResourceFilter(key: 'buyer_organization_id', label: 'Buyer', lookup: organizationLookup),
          AdminResourceFilter(key: 'configurator_template_id', label: 'Template', lookup: configuratorTemplateLookup),
          AdminResourceFilter(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
          AdminResourceFilter(key: 'status_code', label: 'Status', options: quoteStatusOptions),
          AdminResourceFilter(key: 'order_type_code', label: 'Order type', options: quoteOrderTypeOptions),
        ],
        formFields: [
          AdminField(key: 'quote_no', label: 'Quote no', readOnly: true),
          AdminField(key: 'seller_organization_id', label: 'Seller', lookup: organizationLookup, readOnly: true),
          AdminField(key: 'buyer_organization_id', label: 'Buyer', lookup: organizationLookup, readOnly: true),
          AdminField(key: 'configurator_template_id', label: 'Template', lookup: configuratorTemplateLookup, readOnly: true),
          AdminField(key: 'price_list_id', label: 'Price list', lookup: priceListLookup, readOnly: true),
          AdminField(key: 'order_type_code', label: 'Order type', readOnly: true),
          AdminField(key: 'status_code', label: 'Status', readOnly: true),
          AdminField(key: 'currency', label: 'Currency', readOnly: true),
          AdminField(key: 'quote_date', label: 'Quote date', type: AdminFieldType.date, readOnly: true),
          AdminField(key: 'expires_at', label: 'Expires at', type: AdminFieldType.date, readOnly: true),
          AdminField(key: 'totals_json', label: 'Totals JSON', type: AdminFieldType.json, readOnly: true),
          AdminField(key: 'input_json', label: 'Input JSON', type: AdminFieldType.json, readOnly: true),
          AdminField(key: 'result_json', label: 'Result JSON', type: AdminFieldType.json, readOnly: true),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show quote lines',
            targetResourceKey: 'quote_lines',
            filterKey: 'quote_id',
            sourceValueKey: 'id',
            icon: Icons.format_list_bulleted_rounded,
          ),
          AdminDetailAction(
            label: 'Show quote events',
            targetResourceKey: 'quote_events',
            filterKey: 'quote_id',
            sourceValueKey: 'id',
            icon: Icons.event_note_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'quote_lines',
        title: 'Quote Lines',
        endpoint: '/api/admin/quote-lines',
        icon: Icons.format_list_bulleted_rounded,
        supportsCreate: false,
        supportsEdit: false,
        supportsDelete: false,
        columns: [
          AdminColumn(key: 'quote_id', label: 'Quote', flex: 2, lookup: quoteLookup),
          AdminColumn(key: 'section_code', label: 'Section'),
          AdminColumn(key: 'description', label: 'Description', isPrimary: true, flex: 3),
          AdminColumn(key: 'quantity', label: 'Qty'),
          AdminColumn(key: 'unit_code', label: 'Unit'),
          AdminColumn(key: 'unit_price', label: 'Unit price'),
          AdminColumn(key: 'amount', label: 'Amount'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'quote_id', label: 'Quote', lookup: quoteLookup),
          AdminResourceFilter(key: 'catalog_item_id', label: 'Catalog item', lookup: catalogItemLookup),
          AdminResourceFilter(key: 'catalog_variant_id', label: 'Catalog variant', lookup: catalogVariantLookup),
        ],
        formFields: [
          AdminField(key: 'quote_id', label: 'Quote', lookup: quoteLookup, readOnly: true),
          AdminField(key: 'section_code', label: 'Section', readOnly: true),
          AdminField(key: 'description', label: 'Description', type: AdminFieldType.longText, readOnly: true),
          AdminField(key: 'catalog_item_id', label: 'Catalog item', lookup: catalogItemLookup, readOnly: true),
          AdminField(key: 'catalog_variant_id', label: 'Catalog variant', lookup: catalogVariantLookup, readOnly: true),
          AdminField(key: 'color_code', label: 'Color', readOnly: true),
          AdminField(key: 'width_mm', label: 'Width mm', type: AdminFieldType.number, readOnly: true),
          AdminField(key: 'depth_mm', label: 'Depth mm', type: AdminFieldType.number, readOnly: true),
          AdminField(key: 'quantity', label: 'Quantity', type: AdminFieldType.number, readOnly: true),
          AdminField(key: 'unit_code', label: 'Unit', readOnly: true),
          AdminField(key: 'unit_price', label: 'Unit price', type: AdminFieldType.number, readOnly: true),
          AdminField(key: 'amount', label: 'Amount', type: AdminFieldType.number, readOnly: true),
          AdminField(key: 'meta_json', label: 'Meta JSON', type: AdminFieldType.json, readOnly: true),
        ],
      ),
      AdminResourceDefinition(
        key: 'quote_events',
        title: 'Quote Events',
        endpoint: '/api/admin/quote-events',
        icon: Icons.event_note_outlined,
        supportsCreate: false,
        supportsEdit: false,
        supportsDelete: false,
        columns: [
          AdminColumn(key: 'quote_id', label: 'Quote', flex: 2, lookup: quoteLookup),
          AdminColumn(key: 'event_type_code', label: 'Event', isPrimary: true, flex: 2),
          AdminColumn(key: 'event_status_code', label: 'Status'),
          AdminColumn(key: 'actor_user_id', label: 'Actor', flex: 2, lookup: userLookup),
          AdminColumn(key: 'event_at', label: 'Event at', flex: 2),
        ],
        listFilters: [
          AdminResourceFilter(key: 'quote_id', label: 'Quote', lookup: quoteLookup),
          AdminResourceFilter(key: 'actor_user_id', label: 'Actor', lookup: userLookup),
        ],
        formFields: [
          AdminField(key: 'quote_id', label: 'Quote', lookup: quoteLookup, readOnly: true),
          AdminField(key: 'event_type_code', label: 'Event type', readOnly: true),
          AdminField(key: 'event_status_code', label: 'Event status', readOnly: true),
          AdminField(key: 'event_at', label: 'Event at', readOnly: true),
          AdminField(key: 'actor_user_id', label: 'Actor', lookup: userLookup, readOnly: true),
          AdminField(key: 'payload_json', label: 'Payload JSON', type: AdminFieldType.json, readOnly: true),
          AdminField(key: 'notes', label: 'Notes', type: AdminFieldType.longText, readOnly: true),
        ],
      ),
    ],
  ),
// END quote admin block: admin-registry-quote-nav-v2
  AdminNavGroup(
    key: 'catalog',
    title: 'Catalog',
    icon: Icons.inventory_2_outlined,
    resources: [
      AdminResourceDefinition(
        key: 'catalog_items',
        title: 'Catalog Items',
        endpoint: '/api/admin/catalog-items',
        icon: Icons.view_list_rounded,
        columns: [
          AdminColumn(key: 'base_code', label: 'Base code', isPrimary: true, flex: 2),
          AdminColumn(key: 'name', label: 'Name', flex: 3),
          AdminColumn(key: 'product_family_id', label: 'Product family', flex: 2, lookup: productFamilyLookup),
          AdminColumn(key: 'category_code', label: 'Category'),
          AdminColumn(key: 'system_code', label: 'System'),
          AdminColumn(key: 'measure_type_code', label: 'Unit'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'id', label: 'Catalog item', lookup: catalogItemLookup),
          AdminResourceFilter(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminResourceFilter(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
          AdminResourceFilter(key: 'item_type_code', label: 'Item type', options: catalogItemTypeOptions),
        ],
        formFields: [
          AdminField(
            key: 'price_list_id',
            label: 'Related price list',
            lookup: priceListLookup,
            includeInPayload: false,
            helperText: 'Relation is stored in Price List Items; this field is not saved here.',
          ),
          AdminField(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminField(key: 'base_code', label: 'Base code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'short_name', label: 'Short name'),
          AdminField(key: 'category_code', label: 'Category code'),
          AdminField(key: 'item_type_code', label: 'Item type', options: catalogItemTypeOptions),
          AdminField(key: 'system_code', label: 'System code'),
          AdminField(key: 'measure_type_code', label: 'Measure type', options: unitOptions),
          AdminField(key: 'default_length_mm', label: 'Default length', type: AdminFieldType.number),
          AdminField(key: 'default_color_code', label: 'Default color'),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
          AdminField(key: 'attributes_json', label: 'Attributes JSON', type: AdminFieldType.json),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show catalog variants',
            targetResourceKey: 'catalog_variants',
            filterKey: 'catalog_item_id',
            sourceValueKey: 'id',
            icon: Icons.tune_rounded,
          ),
          AdminDetailAction(
            label: 'Show price list items',
            targetResourceKey: 'price_list_items',
            filterKey: 'catalog_item_id',
            sourceValueKey: 'id',
            icon: Icons.table_rows_outlined,
          ),
          AdminDetailAction(
            label: 'Show price lists',
            targetResourceKey: 'price_lists',
            filterKey: 'catalog_item_id',
            sourceValueKey: 'id',
            icon: Icons.request_quote_outlined,
          ),
          AdminDetailAction(
            label: 'Show product family',
            targetResourceKey: 'product_families',
            filterKey: 'id',
            sourceValueKey: 'product_family_id',
            selectTargetRow: true,
            icon: Icons.category_outlined,
          ),
          AdminDetailAction(
            label: 'Show template',
            targetResourceKey: 'configurator_templates',
            filterKey: 'id',
            sourceValueKey: 'configurator_template_id',
            selectTargetRow: true,
            icon: Icons.webhook_rounded,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'catalog_variants',
        title: 'Catalog Variants',
        endpoint: '/api/admin/catalog-variants',
        icon: Icons.tune_rounded,
        columns: [
          AdminColumn(key: 'variant_sku', label: 'Variant SKU', isPrimary: true, flex: 2),
          AdminColumn(key: 'catalog_item_id', label: 'Catalog item', flex: 2, lookup: catalogItemLookup),
          AdminColumn(key: 'article_no', label: 'Article no'),
          AdminColumn(key: 'color_name', label: 'Color'),
          AdminColumn(key: 'length_mm', label: 'Length'),
          AdminColumn(key: 'glass_type_code', label: 'Glass'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'catalog_item_id', label: 'Catalog item', lookup: catalogItemLookup),
          AdminResourceFilter(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
        ],
        formFields: [
          AdminField(
            key: 'price_list_id',
            label: 'Related price list',
            lookup: priceListLookup,
            includeInPayload: false,
            helperText: 'Relation is stored in Price List Items; this field is not saved here.',
          ),
          AdminField(key: 'catalog_item_id', label: 'Catalog item', lookup: catalogItemLookup),
          AdminField(key: 'variant_sku', label: 'Variant SKU'),
          AdminField(key: 'article_no', label: 'Article no'),
          AdminField(key: 'color_code', label: 'Color code'),
          AdminField(key: 'color_name', label: 'Color name'),
          AdminField(key: 'length_mm', label: 'Length', type: AdminFieldType.number),
          AdminField(key: 'glass_type_code', label: 'Glass type'),
          AdminField(key: 'coating_type_code', label: 'Coating type'),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
          AdminField(key: 'attributes_json', label: 'Attributes JSON', type: AdminFieldType.json),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show catalog item',
            targetResourceKey: 'catalog_items',
            filterKey: 'id',
            sourceValueKey: 'catalog_item_id',
            selectTargetRow: true,
            icon: Icons.view_list_rounded,
          ),
          AdminDetailAction(
            label: 'Show price list items',
            targetResourceKey: 'price_list_items',
            filterKey: 'catalog_variant_id',
            sourceValueKey: 'id',
            icon: Icons.table_rows_outlined,
          ),
          AdminDetailAction(
            label: 'Show price lists',
            targetResourceKey: 'price_lists',
            filterKey: 'catalog_variant_id',
            sourceValueKey: 'id',
            icon: Icons.request_quote_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'catalog_media',
        title: 'Catalog Media',
        endpoint: '/api/admin/catalog-media',
        icon: Icons.perm_media_outlined,
        columns: [
          AdminColumn(key: 'kind', label: 'Kind', isPrimary: true),
          AdminColumn(key: 'catalog_item_id', label: 'Item'),
          AdminColumn(key: 'catalog_variant_id', label: 'Variant'),
          AdminColumn(key: 'file_id', label: 'File'),
          AdminColumn(key: 'is_primary', label: 'Primary'),
        ],
        formFields: [
          AdminField(key: 'catalog_item_id', label: 'Catalog item id'),
          AdminField(key: 'catalog_variant_id', label: 'Catalog variant id'),
          AdminField(key: 'kind', label: 'Kind', options: mediaKindOptions),
          AdminField(key: 'file_id', label: 'File id'),
          AdminField(key: 'sort_order', label: 'Sort order', type: AdminFieldType.number),
          AdminField(key: 'is_primary', label: 'Primary', type: AdminFieldType.boolType),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
        ],
      ),
    ],
  ),
  AdminNavGroup(
    key: 'pricing',
    title: 'Pricing',
    icon: Icons.euro_rounded,
    resources: [
      AdminResourceDefinition(
        key: 'price_lists',
        title: 'Price Lists',
        endpoint: '/api/admin/price-lists',
        icon: Icons.request_quote_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'scope_code', label: 'Scope'),
          AdminColumn(key: 'currency', label: 'Currency'),
          AdminColumn(key: 'organization_id', label: 'Organization', flex: 2, lookup: organizationLookup),
          AdminColumn(key: 'product_family_id', label: 'Family', flex: 2, lookup: productFamilyLookup),
          AdminColumn(key: 'valid_from', label: 'Valid from'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminResourceFilter(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminResourceFilter(key: 'scope_code', label: 'Scope', options: priceListScopeOptions),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'scope_code', label: 'Scope', options: priceListScopeOptions),
          AdminField(key: 'currency', label: 'Currency'),
          AdminField(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminField(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminField(key: 'valid_from', label: 'Valid from', type: AdminFieldType.date),
          AdminField(key: 'valid_to', label: 'Valid to', type: AdminFieldType.date),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show price matrices',
            targetResourceKey: 'price_matrices',
            filterKey: 'price_list_id',
            sourceValueKey: 'id',
            icon: Icons.grid_on_rounded,
          ),
          AdminDetailAction(
            label: 'Show price list items',
            targetResourceKey: 'price_list_items',
            filterKey: 'price_list_id',
            sourceValueKey: 'id',
            icon: Icons.table_rows_outlined,
          ),
          AdminDetailAction(
            label: 'Show organization',
            targetResourceKey: 'organizations',
            filterKey: 'id',
            sourceValueKey: 'organization_id',
            selectTargetRow: true,
            icon: Icons.domain_rounded,
          ),
          AdminDetailAction(
            label: 'Show product family',
            targetResourceKey: 'product_families',
            filterKey: 'id',
            sourceValueKey: 'product_family_id',
            selectTargetRow: true,
            icon: Icons.category_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'price_list_items',
        title: 'Price List Items',
        endpoint: '/api/admin/price-list-items',
        icon: Icons.table_rows_outlined,
        columns: [
          AdminColumn(key: 'target_code', label: 'Target', isPrimary: true, flex: 2),
          AdminColumn(key: 'price_list_id', label: 'Price list', flex: 2, lookup: priceListLookup),
          AdminColumn(key: 'catalog_item_id', label: 'Catalog item', flex: 2, lookup: catalogItemNameLookup),
          AdminColumn(key: 'catalog_variant_id', label: 'Catalog variant', flex: 2, lookup: catalogVariantLookup),
          AdminColumn(key: 'unit_code', label: 'Unit'),
          AdminColumn(key: 'unit_price', label: 'Price'),
          AdminColumn(key: 'discount_pct', label: 'Discount'),
          AdminColumn(key: 'lead_time_code', label: 'Lead time'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
          AdminResourceFilter(key: 'catalog_item_id', label: 'Catalog item', lookup: catalogItemNameLookup),
          AdminResourceFilter(key: 'catalog_variant_id', label: 'Catalog variant', lookup: catalogVariantLookup),
        ],
        formFields: [
          AdminField(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
          AdminField(key: 'catalog_item_id', label: 'Catalog item', lookup: catalogItemNameLookup),
          AdminField(key: 'catalog_variant_id', label: 'Catalog variant', lookup: catalogVariantLookup),
          AdminField(key: 'material_price_dimension_id', label: 'Material price dimension', lookup: materialPriceDimensionLookup),
          AdminField(key: 'target_code', label: 'Target code'),
          AdminField(key: 'unit_code', label: 'Unit', options: unitOptions),
          AdminField(key: 'unit_price', label: 'Unit price', type: AdminFieldType.number),
          AdminField(key: 'purchase_price', label: 'Purchase price', type: AdminFieldType.number),
          AdminField(key: 'discount_pct', label: 'Discount %', type: AdminFieldType.number),
          AdminField(key: 'min_qty', label: 'Min qty', type: AdminFieldType.number),
          AdminField(key: 'variant_match_json', label: 'Variant match JSON', type: AdminFieldType.json),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show price list',
            targetResourceKey: 'price_lists',
            filterKey: 'id',
            sourceValueKey: 'price_list_id',
            selectTargetRow: true,
            icon: Icons.request_quote_outlined,
          ),
          AdminDetailAction(
            label: 'Show catalog item',
            targetResourceKey: 'catalog_items',
            filterKey: 'id',
            sourceValueKey: 'catalog_item_id',
            selectTargetRow: true,
            icon: Icons.view_list_rounded,
          ),
          AdminDetailAction(
            label: 'Show catalog variant',
            targetResourceKey: 'catalog_variants',
            filterKey: 'id',
            sourceValueKey: 'catalog_variant_id',
            selectTargetRow: true,
            icon: Icons.inventory_2_outlined,
          ),
          AdminDetailAction(
            label: 'Show material dimension',
            targetResourceKey: 'material_price_dimensions',
            filterKey: 'id',
            sourceValueKey: 'material_price_dimension_id',
            selectTargetRow: true,
            icon: Icons.straighten_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'price_matrices',
        title: 'Price Matrices',
        endpoint: '/api/admin/price-matrices',
        icon: Icons.grid_on_rounded,
        columns: [
          AdminColumn(key: 'matrix_code', label: 'Matrix code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'price_list_id', label: 'Price list', flex: 2, lookup: priceListLookup),
          AdminColumn(key: 'parser_kind', label: 'Parser'),
          AdminColumn(key: 'section_code', label: 'Section'),
          AdminColumn(key: 'source_sheet_name', label: 'Sheet', flex: 2),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
        ],
        formFields: [
          AdminField(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
          AdminField(key: 'matrix_code', label: 'Matrix code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'parser_kind', label: 'Parser kind', options: parserKindOptions),
          AdminField(key: 'phase_label', label: 'Phase label'),
          AdminField(key: 'product_label', label: 'Product label'),
          AdminField(key: 'subtitle_label', label: 'Subtitle label'),
          AdminField(key: 'section_label', label: 'Section label'),
          AdminField(key: 'section_code', label: 'Section code'),
          AdminField(key: 'source_sheet_name', label: 'Source sheet'),
          AdminField(key: 'source_row_no', label: 'Source row', type: AdminFieldType.number),
          AdminField(key: 'source_col_no', label: 'Source col', type: AdminFieldType.number),
          AdminField(key: 'sort_order', label: 'Sort order', type: AdminFieldType.number),
          AdminField(key: 'header_json', label: 'Header JSON', type: AdminFieldType.json),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        description: 'Матрицы цен, импортированные из spreadsheet-блоков или подготовленные вручную.',
      ),
      AdminResourceDefinition(
        key: 'price_matrix_cells',
        title: 'Price Matrix Cells',
        endpoint: '/api/admin/price-matrix-cells',
        icon: Icons.apps_rounded,
        columns: [
          AdminColumn(key: 'cell_ref', label: 'Cell', isPrimary: true),
          AdminColumn(key: 'row_no', label: 'Row'),
          AdminColumn(key: 'col_no', label: 'Col'),
          AdminColumn(key: 'width_mm', label: 'Width'),
          AdminColumn(key: 'depth_mm', label: 'Depth'),
          AdminColumn(key: 'unit_price', label: 'Price'),
        ],
        formFields: [
          AdminField(key: 'price_matrix_id', label: 'Price matrix id'),
          AdminField(key: 'row_no', label: 'Row no', type: AdminFieldType.number),
          AdminField(key: 'col_no', label: 'Col no', type: AdminFieldType.number),
          AdminField(key: 'cell_ref', label: 'Cell ref'),
          AdminField(key: 'width_mm', label: 'Width', type: AdminFieldType.number),
          AdminField(key: 'height_mm', label: 'Height', type: AdminFieldType.number),
          AdminField(key: 'depth_mm', label: 'Depth', type: AdminFieldType.number),
          AdminField(key: 'depth_m', label: 'Depth m', type: AdminFieldType.number),
          AdminField(key: 'width_bucket_code', label: 'Width bucket code'),
          AdminField(key: 'beam_count', label: 'Beam count', type: AdminFieldType.number),
          AdminField(key: 'post_count', label: 'Post count', type: AdminFieldType.number),
          AdminField(key: 'unit_price', label: 'Unit price', type: AdminFieldType.number),
          AdminField(key: 'dimensions_json', label: 'Dimensions JSON', type: AdminFieldType.json),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
        ],
        description: 'Ячейки матрицы: row / col, размеры, бакеты и итоговая цена.',
      ),
      AdminResourceDefinition(
        key: 'special_prices',
        title: 'Special Prices',
        endpoint: '/api/admin/special-prices',
        icon: Icons.local_offer_outlined,
        columns: [
          AdminColumn(key: 'target_code', label: 'Target', isPrimary: true),
          AdminColumn(key: 'organization_id', label: 'Organization'),
          AdminColumn(key: 'currency', label: 'Currency'),
          AdminColumn(key: 'unit_price', label: 'Price'),
          AdminColumn(key: 'valid_from', label: 'Valid from'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminField(key: 'relation_id', label: 'Relation id'),
          AdminField(key: 'product_family_id', label: 'Product family id'),
          AdminField(key: 'catalog_item_id', label: 'Catalog item id'),
          AdminField(key: 'catalog_variant_id', label: 'Catalog variant id'),
          AdminField(key: 'target_code', label: 'Target code'),
          AdminField(key: 'currency', label: 'Currency'),
          AdminField(key: 'unit_code', label: 'Unit', options: unitOptions),
          AdminField(key: 'unit_price', label: 'Unit price', type: AdminFieldType.number),
          AdminField(key: 'discount_pct', label: 'Discount %', type: AdminFieldType.number),
          AdminField(key: 'valid_from', label: 'Valid from', type: AdminFieldType.date),
          AdminField(key: 'valid_to', label: 'Valid to', type: AdminFieldType.date),
          AdminField(key: 'comment', label: 'Comment', type: AdminFieldType.longText),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
      AdminResourceDefinition(
        key: 'discount_profiles',
        title: 'Discount Profiles',
        endpoint: '/api/admin/discount-profiles',
        icon: Icons.percent_rounded,
        columns: [
          AdminColumn(key: 'discount_type_code', label: 'Type', isPrimary: true),
          AdminColumn(key: 'organization_id', label: 'Organization'),
          AdminColumn(key: 'product_family_id', label: 'Family'),
          AdminColumn(key: 'discount_pct', label: 'Discount'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminField(key: 'relation_id', label: 'Relation id'),
          AdminField(key: 'discount_type_code', label: 'Discount type'),
          AdminField(key: 'product_family_id', label: 'Product family id'),
          AdminField(key: 'discount_pct', label: 'Discount %', type: AdminFieldType.number),
          AdminField(key: 'rules_json', label: 'Rules JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
      AdminResourceDefinition(
        key: 'price_calculation_profiles',
        title: 'Calculation Profiles',
        endpoint: '/api/admin/price-calculation-profiles',
        icon: Icons.calculate_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'base_markup_pct', label: 'Markup %'),
          AdminColumn(key: 'vat_pct', label: 'VAT %'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'product_family_id', label: 'Product family id'),
          AdminField(key: 'valid_from', label: 'Valid from', type: AdminFieldType.date),
          AdminField(key: 'valid_to', label: 'Valid to', type: AdminFieldType.date),
          AdminField(key: 'base_markup_pct', label: 'Base markup %', type: AdminFieldType.number),
          AdminField(key: 'base_markup_factor', label: 'Base markup factor', type: AdminFieldType.number),
          AdminField(key: 'promo_markup_pct', label: 'Promo markup %', type: AdminFieldType.number),
          AdminField(key: 'promo_markup_factor', label: 'Promo markup factor', type: AdminFieldType.number),
          AdminField(key: 'vat_pct', label: 'VAT %', type: AdminFieldType.number),
          AdminField(key: 'vat_factor', label: 'VAT factor', type: AdminFieldType.number),
          AdminField(key: 'extra_costs_json', label: 'Extra costs JSON', type: AdminFieldType.json),
          AdminField(key: 'settings_json', label: 'Settings JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
    ],
  ),
  AdminNavGroup(
    key: 'rules',
    title: 'Rules & Templates',
    icon: Icons.rule_folder_outlined,
    resources: [
      AdminResourceDefinition(
        key: 'configurator_templates',
        title: 'Configurator Templates',
        endpoint: '/api/admin/configurator-templates',
        icon: Icons.webhook_rounded,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'product_family_id', label: 'Family', flex: 2, lookup: productFamilyLookup),
          AdminColumn(key: 'roof_model_id', label: 'Roof model', flex: 2, lookup: roofModelLookup),
          AdminColumn(key: 'version', label: 'Version'),
          AdminColumn(key: 'status_code', label: 'Status'),
          AdminColumn(key: 'source_sheet_name', label: 'Source sheet'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminResourceFilter(key: 'status_code', label: 'Status', options: statusOptions),
        ],
        formFields: [
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminField(key: 'source_sheet_name', label: 'Source sheet name'),
          AdminField(key: 'source_range', label: 'Source range'),
          AdminField(key: 'version', label: 'Version', type: AdminFieldType.number),
          AdminField(key: 'status_code', label: 'Status', options: statusOptions),
          AdminField(key: 'ui_schema_json', label: 'UI schema JSON', type: AdminFieldType.json),
          AdminField(key: 'default_values_json', label: 'Default values JSON', type: AdminFieldType.json),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show product family',
            targetResourceKey: 'product_families',
            filterKey: 'id',
            sourceValueKey: 'product_family_id',
            selectTargetRow: true,
            icon: Icons.category_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'template_modules',
        title: 'Template Modules',
        endpoint: '/api/admin/template-modules',
        icon: Icons.widgets_outlined,
        columns: [
          AdminColumn(key: 'module_code', label: 'Module code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'module_type_code', label: 'Type'),
          AdminColumn(key: 'source_sheet_name', label: 'Sheet'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'configurator_template_id', label: 'Template id'),
          AdminField(key: 'module_code', label: 'Module code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'module_type_code', label: 'Module type', options: moduleTypeOptions),
          AdminField(key: 'source_sheet_name', label: 'Source sheet name'),
          AdminField(key: 'source_range', label: 'Source range'),
          AdminField(key: 'target_range', label: 'Target range'),
          AdminField(key: 'reset_source_range', label: 'Reset source range'),
          AdminField(key: 'ui_config_json', label: 'UI config JSON', type: AdminFieldType.json),
          AdminField(key: 'default_data_json', label: 'Default data JSON', type: AdminFieldType.json),
          AdminField(key: 'sort_order', label: 'Sort order', type: AdminFieldType.number),
          AdminField(key: 'is_editable', label: 'Editable', type: AdminFieldType.boolType),
          AdminField(key: 'is_resettable', label: 'Resettable', type: AdminFieldType.boolType),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
      AdminResourceDefinition(
        key: 'rule_sets',
        title: 'Rule Sets',
        endpoint: '/api/admin/rule-sets',
        icon: Icons.rule_rounded,
        columns: [
          AdminColumn(key: 'version', label: 'Version', isPrimary: true),
          AdminColumn(key: 'configurator_template_id', label: 'Template'),
          AdminColumn(key: 'status_code', label: 'Status'),
          AdminColumn(key: 'valid_from', label: 'Valid from'),
          AdminColumn(key: 'valid_to', label: 'Valid to'),
        ],
        formFields: [
          AdminField(key: 'configurator_template_id', label: 'Configurator template id'),
          AdminField(key: 'version', label: 'Version', type: AdminFieldType.number),
          AdminField(key: 'valid_from', label: 'Valid from', type: AdminFieldType.date),
          AdminField(key: 'valid_to', label: 'Valid to', type: AdminFieldType.date),
          AdminField(key: 'status_code', label: 'Status', options: statusOptions),
          AdminField(key: 'notes', label: 'Notes', type: AdminFieldType.longText),
          AdminField(key: 'rules_json', label: 'Rules JSON', type: AdminFieldType.json),
        ],
      ),
      AdminResourceDefinition(
        key: 'rule_matrices',
        title: 'Rule Matrices',
        endpoint: '/api/admin/rule-matrices',
        icon: Icons.view_module_outlined,
        columns: [
          AdminColumn(key: 'matrix_code', label: 'Matrix code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'source_sheet_name', label: 'Sheet'),
          AdminColumn(key: 'source_range', label: 'Range'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'rule_set_id', label: 'Rule set id'),
          AdminField(key: 'matrix_code', label: 'Matrix code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'source_sheet_name', label: 'Source sheet'),
          AdminField(key: 'source_range', label: 'Source range'),
          AdminField(key: 'axis_x_code', label: 'Axis X code'),
          AdminField(key: 'axis_y_code', label: 'Axis Y code'),
          AdminField(key: 'header_json', label: 'Header JSON', type: AdminFieldType.json),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'sort_order', label: 'Sort order', type: AdminFieldType.number),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
      AdminResourceDefinition(
        key: 'rule_matrix_rows',
        title: 'Rule Matrix Rows',
        endpoint: '/api/admin/rule-matrix-rows',
        icon: Icons.reorder_rounded,
        columns: [
          AdminColumn(key: 'row_no', label: 'Row', isPrimary: true),
          AdminColumn(key: 'rule_matrix_id', label: 'Rule matrix'),
          AdminColumn(key: 'notes', label: 'Notes', flex: 2),
        ],
        formFields: [
          AdminField(key: 'rule_matrix_id', label: 'Rule matrix id'),
          AdminField(key: 'row_no', label: 'Row number', type: AdminFieldType.number),
          AdminField(key: 'key_json', label: 'Key JSON', type: AdminFieldType.json),
          AdminField(key: 'result_json', label: 'Result JSON', type: AdminFieldType.json),
          AdminField(key: 'notes', label: 'Notes', type: AdminFieldType.longText),
        ],
      ),
    ],
  ),
  AdminNavGroup(
    key: 'references',
    title: 'References',
    icon: Icons.library_books_outlined,
    resources: [
      AdminResourceDefinition(
        key: 'reference_domains',
        title: 'Reference Domains',
        endpoint: '/api/admin/reference-domains',
        icon: Icons.bookmarks_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'is_system', label: 'System'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'description', label: 'Description', type: AdminFieldType.longText),
          AdminField(key: 'is_system', label: 'System', type: AdminFieldType.boolType),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
      AdminResourceDefinition(
        key: 'reference_values',
        title: 'Reference Values',
        endpoint: '/api/admin/reference-values',
        icon: Icons.data_object_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'label', label: 'Label', flex: 2),
          AdminColumn(key: 'domain_id', label: 'Domain'),
          AdminColumn(key: 'sort_order', label: 'Sort'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          //AdminField(key: 'domain_id', label: 'Domain id'),
          AdminField(key: 'domain_id', label: 'Domain', lookup: referenceDomainLookup),
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'label', label: 'Label'),
          AdminField(key: 'alt_label', label: 'Alt label'),
          AdminField(key: 'sort_order', label: 'Sort order', type: AdminFieldType.number),
          AdminField(key: 'color_hex', label: 'Color HEX'),
          AdminField(key: 'numeric_value', label: 'Numeric value', type: AdminFieldType.number),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
      AdminResourceDefinition(
        key: 'product_families',
        title: 'Product Families',
        endpoint: '/api/admin/product-families',
        icon: Icons.category_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'sort_order', label: 'Sort'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
          AdminResourceFilter(key: 'configurator_template_id', label: 'Configurator template', lookup: configuratorTemplateLookup),
          AdminResourceFilter(key: 'organization_id', label: 'Organization access', lookup: organizationLookup),
          AdminResourceFilter(key: 'material_price_dimension_id', label: 'Material price dimension', lookup: materialPriceDimensionLookup),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(
            key: 'price_list_id',
            label: 'Related price list',
            lookup: priceListLookup,
            includeInPayload: false,
            helperText: 'Reverse relation; edit the selected row in Price Lists.',
          ),
          AdminField(
            key: 'configurator_template_id',
            label: 'Related configurator template',
            lookup: configuratorTemplateLookup,
            includeInPayload: false,
            helperText: 'Reverse relation; edit the selected row in Configurator Templates.',
          ),
          AdminField(
            key: 'organization_id',
            label: 'Related organization access',
            lookup: organizationLookup,
            includeInPayload: false,
            helperText: 'Relation is stored in Organization Product Access.',
          ),
          AdminField(
            key: 'roof_model_id',
            label: 'Related roof model',
            lookup: roofModelLookup,
            includeInPayload: false,
            helperText: 'Reverse relation; edit the selected row in Roof Models.',
          ),
          AdminField(
            key: 'material_price_dimension_id',
            label: 'Related material price dimension',
            lookup: materialPriceDimensionLookup,
            includeInPayload: false,
            helperText: 'Reverse relation; edit the selected row in Material Price Dimensions.',
          ),
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'sort_order', label: 'Sort order', type: AdminFieldType.number),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show catalog items',
            targetResourceKey: 'catalog_items',
            filterKey: 'product_family_id',
            sourceValueKey: 'id',
            icon: Icons.view_list_rounded,
          ),
          AdminDetailAction(
            label: 'Show price lists',
            targetResourceKey: 'price_lists',
            filterKey: 'product_family_id',
            sourceValueKey: 'id',
            icon: Icons.request_quote_outlined,
          ),
          AdminDetailAction(
            label: 'Show templates',
            targetResourceKey: 'configurator_templates',
            filterKey: 'product_family_id',
            sourceValueKey: 'id',
            icon: Icons.webhook_rounded,
          ),
          AdminDetailAction(
            label: 'Show organization access',
            targetResourceKey: 'organization_product_access',
            filterKey: 'product_family_id',
            sourceValueKey: 'id',
            icon: Icons.link_rounded,
          ),
          AdminDetailAction(
            label: 'Show roof models',
            targetResourceKey: 'roof_models',
            filterKey: 'product_family_id',
            sourceValueKey: 'id',
            icon: Icons.roofing_outlined,
          ),
          AdminDetailAction(
            label: 'Show material dimensions',
            targetResourceKey: 'material_price_dimensions',
            filterKey: 'product_family_id',
            sourceValueKey: 'id',
            icon: Icons.straighten_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'roof_models',
        title: 'Roof Models',
        endpoint: '/api/admin/roof-models',
        icon: Icons.roofing_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'product_family_id', label: 'Family', flex: 2, lookup: productFamilyLookup),
          AdminColumn(key: 'sort_order', label: 'Sort'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'sort_order', label: 'Sort order', type: AdminFieldType.number),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show product family',
            targetResourceKey: 'product_families',
            filterKey: 'id',
            sourceValueKey: 'product_family_id',
            selectTargetRow: true,
            icon: Icons.category_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'material_price_dimensions',
        title: 'Material Price Dimensions',
        endpoint: '/api/admin/material-price-dimensions',
        icon: Icons.straighten_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'unit_code', label: 'Unit'),
          AdminColumn(key: 'product_family_id', label: 'Family', flex: 2, lookup: productFamilyLookup),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'unit_code', label: 'Unit', options: unitOptions),
          AdminField(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show product family',
            targetResourceKey: 'product_families',
            filterKey: 'id',
            sourceValueKey: 'product_family_id',
            selectTargetRow: true,
            icon: Icons.category_outlined,
          ),
        ],
      ),
    ],
  ),
  AdminNavGroup(
    key: 'organizations',
    title: 'Organizations',
    icon: Icons.apartment_outlined,
    resources: [
      AdminResourceDefinition(
        key: 'organizations',
        title: 'Organizations',
        endpoint: '/api/admin/organizations',
        icon: Icons.domain_rounded,
        columns: [
          AdminColumn(key: 'display_name', label: 'Display name', isPrimary: true, flex: 2),
          AdminColumn(key: 'legal_name', label: 'Legal name', flex: 2),
          AdminColumn(key: 'organization_type', label: 'Type'),
          AdminColumn(key: 'is_internal', label: 'Internal'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(
            key: 'price_list_id',
            label: 'Related price list',
            lookup: priceListLookup,
            includeInPayload: false,
            helperText: 'Reverse relation; edit the selected row in Price Lists.',
          ),
          AdminField(
            key: 'product_family_id',
            label: 'Product family access',
            lookup: productFamilyLookup,
            includeInPayload: false,
            helperText: 'Relation is stored in Organization Product Access.',
          ),
          AdminField(key: 'display_name', label: 'Display name'),
          AdminField(key: 'legal_name', label: 'Legal name'),
          AdminField(key: 'organization_type', label: 'Organization type', options: organizationTypeOptions),
          AdminField(key: 'parent_organization_id', label: 'Parent organization id', lookup: organizationLookup),
          AdminField(key: 'tax_no', label: 'Tax no'),
          AdminField(key: 'vat_no', label: 'VAT no'),
          AdminField(key: 'website', label: 'Website'),
          AdminField(key: 'notes', label: 'Notes', type: AdminFieldType.longText),
          AdminField(key: 'settings_json', label: 'Settings JSON', type: AdminFieldType.json),
          AdminField(key: 'external_refs_json', label: 'External refs JSON', type: AdminFieldType.json),
          AdminField(key: 'is_internal', label: 'Internal', type: AdminFieldType.boolType),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        listFilters: [
          AdminResourceFilter(key: 'id', label: 'Organization', lookup: organizationLookup),
          AdminResourceFilter(key: 'price_list_id', label: 'Price list', lookup: priceListLookup),
          AdminResourceFilter(key: 'parent_organization_id', label: 'Parent organization', lookup: organizationLookup),
          AdminResourceFilter(key: 'organization_type', label: 'Organization type', options: organizationTypeOptions),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show contacts',
            targetResourceKey: 'organization_contacts',
            filterKey: 'organization_id',
            sourceValueKey: 'id',
            icon: Icons.contacts_outlined,
          ),
          AdminDetailAction(
            label: 'Show users',
            targetResourceKey: 'user_organizations',
            filterKey: 'organization_id',
            sourceValueKey: 'id',
            icon: Icons.group_outlined,
          ),
          AdminDetailAction(
            label: 'Show branding',
            targetResourceKey: 'organization_branding',
            filterKey: 'organization_id',
            sourceValueKey: 'id',
            icon: Icons.palette_outlined,
          ),
          AdminDetailAction(
            label: 'Show price lists',
            targetResourceKey: 'price_lists',
            filterKey: 'organization_id',
            sourceValueKey: 'id',
            icon: Icons.request_quote_outlined,
          ),
          AdminDetailAction(
            label: 'Show product access',
            targetResourceKey: 'organization_product_access',
            filterKey: 'organization_id',
            sourceValueKey: 'id',
            icon: Icons.category_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'organization_product_access',
        title: 'Organization Product Access',
        endpoint: '/api/admin/organization-product-access',
        icon: Icons.link_rounded,
        columns: [
          AdminColumn(key: 'organization_id', label: 'Organization', isPrimary: true, flex: 2, lookup: organizationLookup),
          AdminColumn(key: 'product_family_id', label: 'Product family', flex: 2, lookup: productFamilyLookup),
          AdminColumn(key: 'enabled', label: 'Enabled'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminResourceFilter(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminResourceFilter(key: 'enabled', label: 'Enabled', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminField(key: 'product_family_id', label: 'Product family', lookup: productFamilyLookup),
          AdminField(key: 'enabled', label: 'Enabled', type: AdminFieldType.boolType),
          AdminField(key: 'settings_json', label: 'Settings JSON', type: AdminFieldType.json),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show organization',
            targetResourceKey: 'organizations',
            filterKey: 'id',
            sourceValueKey: 'organization_id',
            selectTargetRow: true,
            icon: Icons.domain_rounded,
          ),
          AdminDetailAction(
            label: 'Show product family',
            targetResourceKey: 'product_families',
            filterKey: 'id',
            sourceValueKey: 'product_family_id',
            selectTargetRow: true,
            icon: Icons.category_outlined,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'organization_branding',
        title: 'Branding',
        endpoint: '/api/admin/organization-branding',
        icon: Icons.palette_outlined,
        columns: [
          AdminColumn(key: 'brand_name', label: 'Brand name', isPrimary: true, flex: 2),
          AdminColumn(key: 'organization_id', label: 'Organization', flex: 2, lookup: organizationLookup),
          AdminColumn(key: 'email_from_name', label: 'Email from'),
          AdminColumn(key: 'is_default', label: 'Default'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminResourceFilter(key: 'is_default', label: 'Default', options: activeFilterOptions),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(
            key: 'organization_id',
            label: 'Organization (optional; auto-created if empty)',
            lookup: organizationLookup,
          ),
          AdminField(key: 'brand_name', label: 'Brand name'),
          AdminField(key: 'logo_file_id', label: 'Logo file id'),
          AdminField(key: 'secondary_logo_file_id', label: 'Secondary logo file id'),
          AdminField(key: 'engraving_text', label: 'Engraving text'),
          AdminField(key: 'primary_color', label: 'Primary color'),
          AdminField(key: 'secondary_color', label: 'Secondary color'),
          AdminField(key: 'offer_footer_html', label: 'Offer footer HTML', type: AdminFieldType.longText),
          AdminField(key: 'email_from_name', label: 'Email from name'),
          AdminField(key: 'email_from_address', label: 'Email from address'),
          AdminField(key: 'branding_json', label: 'Branding JSON', type: AdminFieldType.json),
          AdminField(key: 'is_default', label: 'Default', type: AdminFieldType.boolType),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show organization',
            targetResourceKey: 'organizations',
            filterKey: 'id',
            sourceValueKey: 'organization_id',
            selectTargetRow: true,
            icon: Icons.domain_rounded,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'organization_contacts',
        title: 'Contacts',
        endpoint: '/api/admin/organization-contacts',
        icon: Icons.contacts_outlined,
        columns: [
          AdminColumn(key: 'full_name', label: 'Full name', isPrimary: true, flex: 2),
          AdminColumn(key: 'organization_id', label: 'Organization', flex: 2, lookup: organizationLookup),
          AdminColumn(key: 'contact_type', label: 'Type'),
          AdminColumn(key: 'email', label: 'Email', flex: 2),
          AdminColumn(key: 'phone', label: 'Phone'),
          AdminColumn(key: 'is_primary', label: 'Primary'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminResourceFilter(key: 'user_id', label: 'Linked user', lookup: userLookup),
          AdminResourceFilter(key: 'contact_type', label: 'Contact type', options: contactTypeOptions),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminField(key: 'contact_type', label: 'Contact type', options: contactTypeOptions),
          AdminField(key: 'full_name', label: 'Full name'),
          AdminField(key: 'department', label: 'Department'),
          AdminField(key: 'email', label: 'Email'),
          AdminField(key: 'phone', label: 'Phone'),
          AdminField(key: 'mobile_phone', label: 'Mobile phone'),
          AdminField(key: 'is_primary', label: 'Primary', type: AdminFieldType.boolType),
          AdminField(key: 'notes', label: 'Notes', type: AdminFieldType.longText),
          AdminField(key: 'metadata_json', label: 'Metadata JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show organization',
            targetResourceKey: 'organizations',
            filterKey: 'id',
            sourceValueKey: 'organization_id',
            selectTargetRow: true,
            icon: Icons.domain_rounded,
          ),
          AdminDetailAction(
            label: 'Show linked users',
            targetResourceKey: 'user_organizations',
            filterKey: 'contact_id',
            sourceValueKey: 'id',
            icon: Icons.link_rounded,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'users',
        title: 'Users',
        endpoint: '/api/admin/users',
        icon: Icons.person_outline_rounded,
        columns: [
          AdminColumn(key: 'email', label: 'Email', isPrimary: true, flex: 2),
          AdminColumn(key: 'full_name', label: 'Full name', flex: 2),
          AdminColumn(key: 'role_code', label: 'Global role'),
          AdminColumn(key: 'locale_code', label: 'Locale'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'id', label: 'User', lookup: userLookup),
          AdminResourceFilter(key: 'role_code', label: 'Global role', options: globalRoleOptions),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(key: 'email', label: 'Email'),
          AdminField(key: 'full_name', label: 'Full name'),
          AdminField(key: 'role_code', label: 'Global role', options: globalRoleOptions),
          AdminField(key: 'initial_password', label: 'Initial password (required for new users; sysadmin only)', type: AdminFieldType.password),
          AdminField(key: 'locale_code', label: 'Locale code'),
          AdminField(key: 'timezone_name', label: 'Timezone name'),
          AdminField(key: 'settings_json', label: 'Settings JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show linked contacts',
            targetResourceKey: 'organization_contacts',
            filterKey: 'user_id',
            sourceValueKey: 'id',
            icon: Icons.contacts_outlined,
          ),
          AdminDetailAction(
            label: 'Show organization links',
            targetResourceKey: 'user_organizations',
            filterKey: 'user_id',
            sourceValueKey: 'id',
            icon: Icons.link_rounded,
          ),
        ],
      ),
      AdminResourceDefinition(
        key: 'user_organizations',
        title: 'User Organizations',
        endpoint: '/api/admin/user-organizations',
        icon: Icons.group_outlined,
        columns: [
          AdminColumn(key: 'user_id', label: 'User', isPrimary: true, flex: 2, lookup: userLookup),
          AdminColumn(key: 'organization_id', label: 'Organization', flex: 2, lookup: organizationLookup),
          AdminColumn(key: 'contact_id', label: 'Contact', flex: 2, lookup: organizationContactLookup),
          AdminColumn(key: 'role_code', label: 'Org role'),
          AdminColumn(key: 'is_default', label: 'Default'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        listFilters: [
          AdminResourceFilter(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminResourceFilter(key: 'user_id', label: 'User', lookup: userLookup),
          AdminResourceFilter(key: 'contact_id', label: 'Contact', lookup: organizationContactLookup),
          AdminResourceFilter(key: 'role_code', label: 'Organization role', options: organizationRoleOptions),
          AdminResourceFilter(key: 'is_active', label: 'Active', options: activeFilterOptions),
        ],
        formFields: [
          AdminField(key: 'user_id', label: 'User', lookup: userLookup),
          AdminField(key: 'organization_id', label: 'Organization', lookup: organizationLookup),
          AdminField(key: 'contact_id', label: 'Contact', lookup: organizationContactLookup),
          AdminField(key: 'role_code', label: 'Organization role', options: organizationRoleOptions),
          AdminField(key: 'is_default', label: 'Default for user', type: AdminFieldType.boolType),
          AdminField(key: 'permissions_json', label: 'Permissions JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
        detailActions: [
          AdminDetailAction(
            label: 'Show user',
            targetResourceKey: 'users',
            filterKey: 'id',
            sourceValueKey: 'user_id',
            selectTargetRow: true,
            icon: Icons.person_outline_rounded,
          ),
          AdminDetailAction(
            label: 'Show organization',
            targetResourceKey: 'organizations',
            filterKey: 'id',
            sourceValueKey: 'organization_id',
            selectTargetRow: true,
            icon: Icons.domain_rounded,
          ),
        ],
      ),
    ],
  ),
  AdminNavGroup(
    key: 'docs',
    title: 'Docs & Messaging',
    icon: Icons.description_outlined,
    resources: [
      AdminResourceDefinition(
        key: 'document_templates',
        title: 'Document Templates',
        endpoint: '/api/admin/document-templates',
        icon: Icons.file_copy_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'document_type_code', label: 'Document type'),
          AdminColumn(key: 'scope_code', label: 'Scope'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'document_type_code', label: 'Document type'),
          AdminField(key: 'template_type_code', label: 'Template type', options: templateTypeOptions),
          AdminField(key: 'scope_code', label: 'Scope', options: scopeOptions),
          AdminField(key: 'version', label: 'Version', type: AdminFieldType.number),
          AdminField(key: 'source_asset_file_id', label: 'Source asset file id'),
          AdminField(key: 'template_body', label: 'Template body', type: AdminFieldType.longText),
          AdminField(key: 'settings_json', label: 'Settings JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
      AdminResourceDefinition(
        key: 'email_templates',
        title: 'Email Templates',
        endpoint: '/api/admin/email-templates',
        icon: Icons.email_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'message_type_code', label: 'Message type'),
          AdminColumn(key: 'scope_code', label: 'Scope'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'message_type_code', label: 'Message type'),
          AdminField(key: 'scope_code', label: 'Scope', options: scopeOptions),
          AdminField(key: 'subject_template', label: 'Subject template'),
          AdminField(key: 'body_text_template', label: 'Body text', type: AdminFieldType.longText),
          AdminField(key: 'body_html_template', label: 'Body HTML', type: AdminFieldType.longText),
          AdminField(key: 'settings_json', label: 'Settings JSON', type: AdminFieldType.json),
          AdminField(key: 'version', label: 'Version', type: AdminFieldType.number),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
    ],
  ),
  AdminNavGroup(
    key: 'integrations',
    title: 'Integrations',
    icon: Icons.hub_outlined,
    resources: [
      AdminResourceDefinition(
        key: 'integration_endpoints',
        title: 'Integration Endpoints',
        endpoint: '/api/admin/integration-endpoints',
        icon: Icons.settings_ethernet_outlined,
        columns: [
          AdminColumn(key: 'code', label: 'Code', isPrimary: true),
          AdminColumn(key: 'name', label: 'Name', flex: 2),
          AdminColumn(key: 'provider_code', label: 'Provider'),
          AdminColumn(key: 'entity_scope_code', label: 'Scope'),
          AdminColumn(key: 'is_active', label: 'Active'),
        ],
        formFields: [
          AdminField(key: 'code', label: 'Code'),
          AdminField(key: 'name', label: 'Name'),
          AdminField(key: 'provider_code', label: 'Provider code'),
          AdminField(key: 'entity_scope_code', label: 'Entity scope code'),
          AdminField(key: 'config_json', label: 'Config JSON', type: AdminFieldType.json),
          AdminField(key: 'is_active', label: 'Active', type: AdminFieldType.boolType),
        ],
      ),
      AdminResourceDefinition(
        key: 'integration_jobs',
        title: 'Integration Jobs',
        endpoint: '/api/admin/integration-jobs',
        icon: Icons.sync_outlined,
        columns: [
          AdminColumn(key: 'entity_type_code', label: 'Entity', isPrimary: true),
          AdminColumn(key: 'operation_code', label: 'Operation'),
          AdminColumn(key: 'status_code', label: 'Status'),
          AdminColumn(key: 'attempt_count', label: 'Attempts'),
          AdminColumn(key: 'scheduled_at', label: 'Scheduled'),
        ],
        formFields: [
          AdminField(key: 'integration_endpoint_id', label: 'Endpoint id'),
          AdminField(key: 'quote_id', label: 'Quote id'),
          AdminField(key: 'entity_type_code', label: 'Entity type'),
          AdminField(key: 'entity_id', label: 'Entity id'),
          AdminField(key: 'operation_code', label: 'Operation code'),
          AdminField(key: 'external_key', label: 'External key'),
          AdminField(key: 'payload_json', label: 'Payload JSON', type: AdminFieldType.json),
          AdminField(key: 'status_code', label: 'Status', options: statusOptions),
        ],
        supportsCreate: false,
        supportsEdit: false,
      ),
    ],
  ),
];

final allResources = <AdminResourceDefinition>[
  dashboardResource,
  for (final group in adminNavGroups) ...group.resources,
];

AdminResourceDefinition findResourceByKey(String key) {
  return allResources.firstWhere((resource) => resource.key == key);
}
